extends SceneTree
## Telemetry-Gated Scoping tool. Run headless:
##
##   godot --headless --script res://addons/brisklance/self/scripts/run_asset_scan.gd
##
##   1. scans res://addons/brisklance/self/scenes, res://addons/brisklance/self/prefabs and res://addons/brisklance/self/assets for scannable asset
##      ids (in scenes, .tres resources, and nested resource arrays),
##   2. diffs them against the ThemeProfiles found in res://addons/brisklance/self/assets (an id mapped
##      in the basis profile is considered "has art" and dropped),
##   3. prints a prioritized worklist and writes exports/asset_worklist.md.
##
## Kept as a SceneTree script (not an EditorScript) so CI can run it. It builds a
## throwaway ThemeManager from the on-disk profiles rather than touching the
## autoload.

const SCAN_ROOTS: PackedStringArray = ["res://addons/brisklance/self/scenes", "res://addons/brisklance/self/prefabs", "res://addons/brisklance/self/assets"]
const ASSETS_DIRECTORY := "res://addons/brisklance/self/assets"
const REPORT_PATH := "res://exports/asset_worklist.md"


func _initialize() -> void:
	var references: Array[Dictionary] = []
	for root: String in SCAN_ROOTS:
		references.append_array(AssetIdScanner.scan_directory(root))

	var theme_manager: Node = load("res://addons/brisklance/self/autoloads/theme_manager.gd").new()
	var profiles: Array[ThemeProfile] = load_theme_profiles()
	theme_manager.profile_available = profiles
	var basis := &"(none)"
	if not profiles.is_empty():
		theme_manager.active_profile = profiles[0]
		basis = profiles[0].profile_id

	var tasks := AssetIdScanner.build_task_list(references, theme_manager)
	var report := AssetIdScanner.format_task_list(tasks)
	theme_manager.free()

	print("Asset scan basis profile: ", basis)
	print(report)
	write_report(report, basis, references.size())
	quit(0)


func load_theme_profiles() -> Array[ThemeProfile]:
	var profiles: Array[ThemeProfile] = []
	var directory := DirAccess.open(ASSETS_DIRECTORY)
	if directory == null:
		return profiles
	directory.list_dir_begin()
	var entry := directory.get_next()
	while entry != "":
		if entry.ends_with(".tres"):
			var resource := load(ASSETS_DIRECTORY.path_join(entry))
			var profile := resource as ThemeProfile
			if profile != null:
				profiles.append(profile)
		entry = directory.get_next()
	directory.list_dir_end()
	return profiles


func write_report(p_report: String, p_basis: StringName, p_reference_count: int) -> void:
	DirAccess.make_dir_recursive_absolute(REPORT_PATH.get_base_dir())
	var file := FileAccess.open(REPORT_PATH, FileAccess.WRITE)
	if file == null:
		printerr("run_asset_scan: cannot write ", REPORT_PATH)
		return
	file.store_string("# Asset worklist\n\n")
	file.store_string("Generated by `scripts/run_asset_scan.gd`. ")
	file.store_string("Basis profile: `%s`. Scanned %d id reference(s).\n\n" % [p_basis, p_reference_count])
	file.store_string("```\n%s\n```\n" % p_report)
	print("run_asset_scan: wrote ", REPORT_PATH)
